from classes.embeds.OsuProfileEmbed import OsuProfileEmbed
from classes.embeds.OsuRecentEmbed import OsuRecentEmbed
from classes.embeds.OsuListEmbed import OsuListEmbed
from classes.embeds.OsuPerformanceEmbed import OsuPerformanceEmbed