from commons.embeds.OsuProfileEmbed import OsuProfileEmbed
from commons.embeds.OsuRecentEmbed import OsuRecentEmbed
from commons.embeds.OsuListEmbed import OsuListEmbed
from commons.embeds.OsuPerformanceEmbed import OsuPerformanceEmbed