blank_issues_enabled: false
contact_links:
    - name: Help
      url: https://github.com/NiceAesth/Sunny/discussions/categories/q-a
      about: Sunny not working as you'd expect? Not sure it's a bug? Check the Q&A section!
    - name: Suggestions or feature request
      url: https://github.com/NiceAesth/Sunny/discussions/categories/ideas
      about: Got something you think should change or be added? Search for or start a new discussion!
